#' Human pancreatic islet data
#'
#' This is the Human pancreatic islet dataset (GSM2230757). The raw data contains 20,125 genes and 1,937
#' cells. Here we use the reference and downsampled datasets generated by Huang et al (2018) which contain
#' 2,284 genes and 1,076 cells (available at https://github.com/mohuangx/SAVER-paper/tree/master/SAVER-data).
#' For details about the approach to generate the reference and downsampled
#' datasets, please refer to Huang et al (2018). This data is an object of class list of length two. count.ref is the
#' reference count matrix and count.samp is the downsampled count matrix.
#'
#' @examples
#' data("baron")
#' @author Xiao-Fei zhang, \email{zhangxf@mail.ccnu.edu.cn}
#' @references Baron, Maayan, et al (2016). A single-cell transcriptomic map of the human and mouse pancreas reveals inter-and intra-cell population structure. \emph{Cell systems}, 3(4):346-360.
#' @references Mo Huang et al (2018). SAVER: gene expression recovery for single-cell RNA sequencing.
#'  \emph{Nature Methods}, 15:539-542.
#' @references Xiao-Fei Zhang et al (2018), EnImpute: An ensemble learning method for imputing single cell RNA sequencing data. submmited
#'
"baron"




#' Human ventral midbrain data
#'
#' This is the Human ventral midbrain dataset (GSE76381). The raw data contains 19,531 genes and 1,977 cells.
#' Here we use the reference and downsampled datasets generated by Huang et al (2018) which contain
#' 2,059 genes and 947 cells (available at https://github.com/mohuangx/SAVER-paper/tree/master/SAVER-data).
#' For details about the approach to generate the reference and downsampled
#' datasets, please refer to Huang et al (2018). This data is an object of class list of length two. count.ref is the
#' reference count matrix and count.samp is the downsampled count matrix.
#'
#' @examples
#' data("manno")
#' @author Xiao-Fei zhang, \email{zhangxf@mail.ccnu.edu.cn}
#' @references La Manno, Gioele, et al  (2016). Molecular diversity of midbrain development in mouse, human, and stem cells. Cell 167(2): 566-580.
#' @references Mo Huang et al (2018). SAVER: gene expression recovery for single-cell RNA sequencing.
#'  \emph{Nature Methods}, 15:539-542.
#' @references Xiao-Fei Zhang et al (2018), EnImpute: An ensemble learning method for imputing single cell RNA sequencing data. submmited
#'
"manno"





#' Mouse brain single-cell RNA-seq dataset
#'
#' This is the mouse cortex and hippocampus dataset (http://linnarssonlab.org/cortex/). The raw data contains 19,972
#' genes and 3,005 cells. Here we use the reference and downsampled datasets generated by Huang et al (2018) which contain
#' 3,529 genes and 1,799 cells (available at https://github.com/mohuangx/SAVER-paper/tree/master/SAVER-data). For details about the approach to generate the reference and downsampled
#' datasets, please refer to Huang et al (2018). This data is an object of class list of length two. count.ref is the
#' reference count matrix and count.samp is the downsampled count matrix.
#'
#' @examples
#' data("zeisel")
#' @author Xiao-Fei zhang, \email{zhangxf@mail.ccnu.edu.cn}
#' @references Amit Zeisel et al. (2015). Cell
#' types in the mouse cortex and hippocampus revealed by single-cell RNA-seq.
#' \emph{Science} 347(6226):1138-1142.
#' @references Mo Huang et al (2018). SAVER: gene expression recovery for single-cell RNA sequencing.
#'  \emph{Nature Methods}, 15:539-542.
#' @references Xiao-Fei Zhang et al (2018), EnImpute: An ensemble learning method for imputing single cell RNA sequencing data. submmited
#'
"zeisel"

